### PR TITLE
Add KML track support

### PR DESCRIPTION
**Pull request by schmidtk**
This adds support for parsing both KML 2.2 and 2.3 Track and MultiTrack elements into a `os.feature.DynamicFeature` that can be animated via the timeline.

Other changes:
* `plugin.track.createTrack` API was changed to take an options argument, instead of the old parameter train. Choo choo!
* `plugin.track.addToTrack` was renamed to `plugin.track.addFeaturesToTrack` for clarity.
* Tracks will now use `ol.geom.LineString` if possible (not a multi-track, and doesn't cross the date line) as a performance enhancement. This is particularly useful for 3D mode, since our feature converter recreates all line primitives representing a multi-line on each update. #135 will address the greater issue.

### CODE REVIEW

**Comment by schmidtk** [comment]
Marked as WIP because I'm waiting on some other track changes to come in.

**Comment by welchyd** [comment]
Would it be possible to add an export option for rotation here as well?

**Comment by schmidtk** [comment]
@welchyd I wrote #154 to address current position heading on tracks. That will cover KML import/export of heading, and generating tracks from data with known heading.

**Comment by bradh** [comment]
@schmidtk Is this ready for test?

**Comment by schmidtk** [comment]
Yes, all good now. You should be able to load KML's with Track/MultiTrack elements (2.2 or 2.3), animate them with the timeline, and export them to KML's that will work in Google Earth.

**Comment by bradh** [comment]
Built and ran locally for me with a KML 2.2 track. I did note a UI issue which is probably more general than this (filed at #159), and should not block merging.

With https://raw.githubusercontent.com/mapbox/togeojson/master/test/data/multitrack.kml I see some UI artifacts that look like styles and Document properties being interpreted as features. I would expect to see the tour and the two placemarks, but not the other leaf elements in the tree.

image

A KML 2.3 file from the OGC KML 2.3 test suite worked OK, although there was no feature info displayed. Not sure if that is intended or not.

**Comment by schmidtk** [comment]
We haven't seen that style node issue before, but those should not be in the tree. It's an issue on the surge master deployment as well (https://master-branch-opensphere-ngageoint.surge.sh/), so not introduced here but I'll take a look at it when I get back on Monday. Thanks Brad!

**Comment by bradh** [comment]
I added a ticket for the unexpected nodes (since its independent of this PR) as #163

**Pull request merged**
