### PR TITLE
chore(conformance): Add conformance violation for goog.isDef()

### LINKED ISSUE #165: Add conformance violations for goog.isDef
`goog.isDef(val)`, `goog.isNull(val)`, and `goog.isDefAndNotNull(val)` are all completely unnecessary in even the oldest browsers we have ever supported.

Make these a conformance violation and use `val !== undefined`, `val === null`, and `val !== undefined && val !== null` instead.

### PR DESCRIPTION
**Pull request by bradh**
Update two users.

Also add violation for unused `goog.isNull()` and `goog.isDefAndNotNull()`.

Resolves #165

### CODE REVIEW

**Comment by wallw-bits** [comment]
This is good but it constitutes a breaking build change for other projects, so the commit needs to be marked as such. Additionally, you might mention in the `BREAKING CHANGE` instructions that we have scripts to convert uses of these automatically at https://github.com/schmidtk/opensphere-jscodeshift

**Comment by bradh** [comment]
Power-cycling the PR to see if we can get a passing CI build.

**Comment by wallw-bits** [comment]
@schmidtk already knows what is wrong with the tests and is working it. We'll restart it when that is ready.

**Comment by schmidtk** [comment]
Broken tests will be addressed by the PR's linked in https://github.com/ngageoint/opensphere/issues/709.

**Pull request merged**
