### PR TITLE
fix(xyz): Add support for URLs containing server ranges.

### LINKED ISSUE #86: Tile provider URL should support templated server names and arrays of servers
Often we have a range of tile providers (e.g. OSM provides 3 - [a-c].tile.openstreetmap.org].

Ideally we'd be able to provide just the template.

### PR DESCRIPTION
**Pull request by bradh**
Includes updates to OSM cookbook docs.

Resolves #86.

### CODE REVIEW

**Comment by bradh** [comment]
The PR does contain some tests: https://github.com/ngageoint/opensphere/pull/92/commits/f4a4470b93457b0fc3284ee9ec63b646984153be#diff-af52b62eeed6298ac3ed43c46cb36042

I will look to add more.

**Comment by wallw-bits** [comment]
Ahh, my bad. I was expecting tests for the abstract class, since most of the additions were there.

**Comment by bradh** [comment]
Should I move the tests across? Seemed like most of the similar tests were in the plugin area, and I wanted to make sure there wasn't some issue that hit later in the layer creation process.

**Comment by bradh** [comment]
Didn't move the tests, but added a second commit to improve test coverage.

**Pull request merged**
