### PR TITLE
feat(states): Add timeline lock to states

### LINKED ISSUE #597: Timeline lock not saved to state
Save the animation lock to saved states as a part of Time.
THIN-13358

### PR DESCRIPTION
**Pull request by smithtb**
THIN-13358
Resolves #597 

This requires ngageoint/opensphere-state-schema#11 to work

### CODE REVIEW

**Comment by welchyd** [comment]
Looks like that fixes the test!
Another test is failing though - setting the lock changes the timestamps

**Comment by smithtb** [comment]
Go to http://measly-bread.surge.sh/

Test steps:
1. Set up the timeline and take note of the values. 
2. Enable the "lock" on the timeline with the lock button.
3. Save the state (be sure to include time)
4. Import the state and clear application data
5. Verify that the values from the state match what the timeline was like before the state was saved
6. Try some different combinations (with skips, etc.)

**Comment by arwatts16** [comment]
I tested it and everything worked exactly as I expected it to.

**Comment by mgettman** [comment]
Looks good!

**Pull request merged**
