### PR TITLE
build(gcc): Upgrade Closure helper to use the JS compiler API.

### PR DESCRIPTION
**Pull request by schmidtk**

### CODE REVIEW

**Comment by bradh** [comment]
`Error: Cannot find module '/home/travis/build/ngageoint/opensphere/--compilation_level'`

**Comment by schmidtk** [comment]
Ah right, I missed the other places we're using `os-compile`. Marking this as WIP until I get those args written out as JSON via the resolver.

**Comment by schmidtk** [comment]
https://github.com/ngageoint/opensphere-build-resolver/pull/38 will write test compilation args to JSON.

**Comment by wallw-bits** [comment]
Looks like `src/os/xt/build-xt.js` is getting picked up by one of the globs in `karma.conf.js` and that is causing the test failure.

**Pull request merged**
