### PR TITLE
feat: added optional parameter to addlayer

### PR DESCRIPTION
**Pull request by raffyl99**
@schmidtk 
Per our email exchange regarding parameter for addlayer.

### CODE REVIEW

**Comment by schmidtk** [comment]
@raffyl99 It looks like the build failed due to a commit message error. I'm not sure why the git hook didn't error on commit, but the fix is to lowercase the subject (`Added -> added`). Could you amend the commit message and push again?

**Comment by raffyl99** [comment]
@schmidtk.  Thanks.  Just resubmitted.

**Comment by schmidtk** [comment]
@raffyl99 Oh, sorry the actual commit message is what we check with `commitlint`. You'll have to `git commit --amend`, update the message, then force push to replace the existing commit.

**Comment by raffyl99** [comment]
@schmidtk I don't have access to my repo from here... let me see if I can do that from github...

**Comment by schmidtk** [comment]
@raffyl99 Ahh no problem, I got it updated!

**Comment by raffyl99** [comment]
@schmidtk Cool.  Thanks.

**Review by schmidtk — APPROVED** [review]

**Comment by raffyl99** [comment]
Thanks.  How often does MIST on the high side pull and merge from this repo?

**Pull request merged**
